#!/usr/bin/env python3
"""
build_eleni.py -- the builder for the Genesis-LLM circle (Eleni).

The circle lives in one HTML file (circle/circle_gate.html). This builder does
NOT rewrite it -- it reads it, PROVES its invariants, and stamps a build card so
the rest of the world can trust the circle without opening it.

    - counts the tongues baked into the ring (the STONE table)
    - reads each tongue's speaker figure and sums coverage vs world population
    - verifies THE LAW: gate weight is exactly 0.700 (GATE_W in the file)
    - honors AXIOM 08: it reads THAT the gate exists; it never renders its meaning
    - writes generated/build_card.json + a human-readable generated/CIRCLE.md

Stdlib only (Python 3.11+). No pip, ever. LF output (Pattern 3).

    py -3 build_eleni.py            # build the card
    py -3 build_eleni.py --check    # verify only, write nothing
"""
from __future__ import annotations
import re, json, sys, hashlib, argparse
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CIRCLE = ROOT / "circle" / "circle_gate.html"
OUT = ROOT / "generated"
WORLD_POP_M = 8000.0  # millions, matches the circle's coverage meter

GATE_LAW = 0.700  # Galactic Law: the gate weight. Non-negotiable.


def read_circle() -> str:
    if not CIRCLE.exists():
        sys.exit("ERROR: missing " + str(CIRCLE.relative_to(ROOT)))
    return CIRCLE.read_text(encoding="utf-8")


def parse_gate(src: str) -> float:
    # find GATE_W = 0.7 anywhere (it may share a var declaration, e.g.
    # "var langIdx = 0, GATE_W = 0.7;"). accept 0.7 or 0.700.
    m = re.search(r"GATE_W\s*=\s*([0-9]*\.?[0-9]+)", src)
    if not m:
        sys.exit("ERROR: GATE_W not found in circle -- cannot verify the law")
    return float(m.group(1))


def parse_stone(src: str):
    """Pull the STONE table rows: [code, name, speakers, text].
    We only need code/name/speakers for the card -- NOT the verse text, and
    NOTHING about the center. Honest, minimal read."""
    # locate the STONE array block
    start = src.find("var STONE")
    if start < 0:
        sys.exit("ERROR: STONE table not found")
    block = src[start: src.find("];", start)]
    # rows look like: ["EN", "English", 380, "..."],
    rows = re.findall(r'\[\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*([0-9]+)\s*,', block)
    tongues = []
    for code, name, sp in rows:
        tongues.append({"code": code, "name": name, "speakers_m": int(sp)})
    return tongues


def coverage(tongues) -> dict:
    seen = {}
    total = 0
    for t in tongues:
        if t["name"] not in seen:
            seen[t["name"]] = 1
            total += t["speakers_m"]
    pct = (total / WORLD_POP_M) * 100.0
    return {"speakers_m_sum": total, "world_pop_m": WORLD_POP_M, "pct": round(pct, 1)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = ap.parse_args()

    src = read_circle()
    gate = parse_gate(src)
    tongues = parse_stone(src)
    cov = coverage(tongues)
    fp = hashlib.sha256(src.encode("utf-8")).hexdigest()[:12]

    # THE LAW: gate must be 0.700
    law_ok = abs(gate - GATE_LAW) < 1e-9
    print("Eleni build")
    print("  circle fingerprint : " + fp)
    print("  tongues baked      : " + str(len(tongues)))
    print("  humanity reached   : " + str(cov["pct"]) + "%")
    print("  gate weight        : " + ("%.3f" % gate) +
          ("  [LAW OK]" if law_ok else "  [!! LAW BROKEN -- expected 0.700]"))
    print("  axiom 08           : center meaning NOT read, NOT rendered (honored)")

    if not law_ok:
        sys.exit("ABORT: gate weight is not 0.700. The circle does not satisfy the law.")

    if args.check:
        print("  --check: verified, wrote nothing.")
        return

    OUT.mkdir(exist_ok=True)
    card = {
        "name": "Eleni",
        "greek": "\u1f19\u03bb\u03ad\u03bd\u03b7",
        "what": "the Genesis-LLM circle: gate (0.700) + a ring of 0/1 nodes, the stone in the tongues of humanity",
        "circle_file": "circle/circle_gate.html",
        "circle_fingerprint": fp,
        "tongues_count": len(tongues),
        "coverage": cov,
        "gate_weight": gate,
        "gate_law": GATE_LAW,
        "law_ok": law_ok,
        "axiom_08": "the center's meaning is never rendered, logged, or displayed",
        "built_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "tongues": tongues,
    }
    (OUT / "build_card.json").write_text(
        json.dumps(card, ensure_ascii=True, indent=2) + "\n", encoding="utf-8", newline="\n")

    lines = []
    lines.append("# Eleni -- circle build card")
    lines.append("")
    lines.append("*generated by build_eleni.py -- do not edit by hand*")
    lines.append("")
    lines.append("- circle fingerprint: `" + fp + "`")
    lines.append("- tongues baked: **" + str(len(tongues)) + "**")
    lines.append("- humanity reached: **" + str(cov["pct"]) + "%** "
                 "(" + str(cov["speakers_m_sum"]) + "M / " + str(int(WORLD_POP_M)) + "M, rough L1)")
    lines.append("- gate weight: **" + ("%.3f" % gate) + "** " + ("[LAW OK]" if law_ok else "[BROKEN]"))
    lines.append("- Axiom 08: the center's meaning is never rendered.")
    lines.append("")
    lines.append("## Tongues on the ring")
    lines.append("")
    lines.append("| code | name | speakers (M) |")
    lines.append("|------|------|--------------|")
    for t in tongues:
        lines.append("| " + t["code"] + " | " + t["name"] + " | " + str(t["speakers_m"]) + " |")
    lines.append("")
    lines.append("*P=12 . chi=2 . the center holds and is not shown . always*")
    (OUT / "CIRCLE.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    print("  wrote generated/build_card.json + generated/CIRCLE.md")


if __name__ == "__main__":
    main()
